services:
  grafana:
    user: root
    container_name: 'beta-qrcode-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.1.4}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/beta-qrcode-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/beta-qrcode-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.beta-qrcode-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: beta-qrcode-panel
